# Generated by Django 5.2.4 on 2025-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sudokumodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudokumodel',
            name='Board',
        ),
        migrations.AddField(
            model_name='sudokumodel',
            name='Boards',
            field=models.TextField(default=None, null=True),
        ),
    ]
