# Generated by Django 5.2.4 on 2025-07-10 07:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sudokumodel_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokumodel',
            name='Boards',
            field=models.JSONField(default=api.models.default_boards),
        ),
    ]
